### ISSUE TITLE
백엔드에서 받아온 Todo data를 redux store에 저장하기

### ISSUE THREAD

**Issue by tTab1204** [tTab1204/paywork-todo#12]
## 설명
todo-list에 새로운 todo를 넣었을 때 redux-store가 즉시 갱신되지 않는 버그 발생

## 할 일
- [x] 백엔드에서 받아온 Todo data를 redux store에 저장하기
- [ ] todo-list에 새로운 todo를 넣었을 때 redux-store 즉시 갱신
- [ ] 데이터 추가에 따른 화면 즉시 렌더링 필요
